# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'demoapp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'demoappTests' do
    inherit! :complete
    # Pods for testing
        pod 'SmartPush-iOS-SDK', '~> 3.5.5'
        pod 'Smartech-iOS-SDK' , '~> 3.5.3'
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end

end
 #service extension target
 target 'SmartechNSE' do
  ###
  
  # Pods for 'YourServiceExtensionTarget'
  pod 'SmartPush-iOS-SDK', '~> 3.5.5'
  
end
 
#content extension target
target 'SmartechNCE' do
  ###
  
  # Pods for 'YourContentExtensionTarget'
    pod 'SmartPush-iOS-SDK', '~> 3.5.5'
    pod 'Smartech-iOS-SDK' , '~> 3.5.3'
    pod 'SmartechNudges', '~> 9.0.8'
    pod 'SmartechAppInbox-iOS-SDK', '~> 3.5.6'
  
end
